export const campusSourceCollections = {
  cyber: 'Cyber Security / Communication',
  bio: 'Bio Informatics',
  ai: 'AI / General Programming / ML-DL / Processing',
} as const;

export type CampusSourceCollection =
  (typeof campusSourceCollections)[keyof typeof campusSourceCollections] | null;

export type CampusInventoryRecord = {
  rowNumber: number;
  title: string;
  author: string;
  publicationInfo: string | null;
  publicationYear: number | null;
  shelfLocationCode: string;
  sourceCollection: CampusSourceCollection;
  ddc: string | null;
};

export const campusInventoryRecords: CampusInventoryRecord[] = [
  {
    rowNumber: 1,
    title: 'Calculus',
    author: 'James Stewart',
    publicationInfo: 'CENGAGE',
    publicationYear: 2014,
    shelfLocationCode: '1/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 2,
    title: 'Physics',
    author: 'James Stewart',
    publicationInfo: 'Learning / CENGAGE',
    publicationYear: 2017,
    shelfLocationCode: '4/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 3,
    title: 'Electronic and Electrical Measurement 1',
    author: 'J.B. GUPTA',
    publicationInfo: 'KATSON, book',
    publicationYear: 1969,
    shelfLocationCode: '2/2',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 4,
    title: 'Electronic and Electrical Measurement 2',
    author: 'J.B. GUPTA',
    publicationInfo: 'KATSON, book',
    publicationYear: 1969,
    shelfLocationCode: '3/2',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 5,
    title: 'Computer System Architecture',
    author: 'M.MORRIS MANO',
    publicationInfo: 'Englewood',
    publicationYear: 1993,
    shelfLocationCode: '3/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 6,
    title: 'Introduction to Radar Systems',
    author: 'MERRILL.SKOLNIK',
    publicationInfo: 'Boston',
    publicationYear: 2001,
    shelfLocationCode: '3/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 7,
    title: 'Information System',
    author: 'RALPH M. STAIR',
    publicationInfo: 'CNGAGE, Learning',
    publicationYear: 2008,
    shelfLocationCode: '3/2',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 8,
    title: 'Designing Embedded Systems with PIC',
    author: 'TIM WILMSHURST',
    publicationInfo: 'Amsterdam',
    publicationYear: 2007,
    shelfLocationCode: '1/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 9,
    title: 'Antenna Theory',
    author: 'CONSTANTINE A. BALANIS',
    publicationInfo: 'Hoboken, New Jersey',
    publicationYear: 2016,
    shelfLocationCode: '2/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 10,
    title: 'Advanced Engineering Mathematics',
    author: 'KREYSZIG, Erwin',
    publicationInfo: 'New Delhi',
    publicationYear: 2006,
    shelfLocationCode: '4/2',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 11,
    title: 'Time Saver Standards For Architectural',
    author: 'Watson, Donald',
    publicationInfo: 'New York',
    publicationYear: 1997,
    shelfLocationCode: '4/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 12,
    title: 'Up And Running With Auto CAD',
    author: 'GINDIS, Elliot',
    publicationInfo: 'United States',
    publicationYear: 2017,
    shelfLocationCode: '3/1',
    sourceCollection: null,
    ddc: null,
  },
  {
    rowNumber: 13,
    title: 'Data And Computer Communications',
    author: 'STALLINGS, WILLIAM',
    publicationInfo: 'Upper Saddle River, N.J',
    publicationYear: 2008,
    shelfLocationCode: '3/1',
    sourceCollection: campusSourceCollections.cyber,
    ddc: null,
  },
  {
    rowNumber: 14,
    title: 'Optical Fiber Communication',
    author: 'KATIYAR, SAPNA',
    publicationInfo: 'New Delhi',
    publicationYear: 2008,
    shelfLocationCode: '3/2',
    sourceCollection: campusSourceCollections.cyber,
    ddc: null,
  },
  {
    rowNumber: 15,
    title: 'Wireless Communications',
    author: 'GOLDSMITH, ANDREA',
    publicationInfo: null,
    publicationYear: 2002,
    shelfLocationCode: '2/1',
    sourceCollection: campusSourceCollections.cyber,
    ddc: null,
  },
  {
    rowNumber: 16,
    title: 'Introduction to Biomedical Engineering',
    author: 'DOMACH, MICHAEL.M',
    publicationInfo: 'India',
    publicationYear: null,
    shelfLocationCode: '2/2',
    sourceCollection: campusSourceCollections.bio,
    ddc: '621',
  },
  {
    rowNumber: 17,
    title: 'Operating System Concepts',
    author: 'SILBERSCHATZ, ABRAHAM',
    publicationInfo: 'India',
    publicationYear: 2016,
    shelfLocationCode: '2/1',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
  {
    rowNumber: 18,
    title: 'Big Java',
    author: 'HORSTMANN, Cay',
    publicationInfo: 'Hoboken, N.J',
    publicationYear: 2006,
    shelfLocationCode: '1,2/1',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
  {
    rowNumber: 19,
    title: 'Programmable Logic Controllers',
    author: 'BOLTON, W.',
    publicationInfo: 'United States Of America',
    publicationYear: 2009,
    shelfLocationCode: '3/2',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
  {
    rowNumber: 20,
    title: 'Structural Analysis',
    author: 'KASSIMALI, ASLAM',
    publicationInfo: 'United States Of America',
    publicationYear: 2011,
    shelfLocationCode: '2/2',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
  {
    rowNumber: 21,
    title: 'Digital Image Processing Using MATLAB',
    author: 'GONZALEZ, Rafael C',
    publicationInfo: '[S.L]',
    publicationYear: 2009,
    shelfLocationCode: '2/1',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
  {
    rowNumber: 22,
    title: 'Programming Language',
    author: 'STROUSTRUP, BJARNE',
    publicationInfo: 'United States Of America',
    publicationYear: 1997,
    shelfLocationCode: '1/2',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
  {
    rowNumber: 23,
    title: 'Analog And Digital Filter Desian',
    author: 'WINDER, STEUE',
    publicationInfo: 'India',
    publicationYear: 2002,
    shelfLocationCode: '1/1',
    sourceCollection: campusSourceCollections.ai,
    ddc: null,
  },
];
